services:
  jupyterhub:
    image: jupyterhub/jupyterhub:latest
    container_name: simarro-jupyterhub
    ports:
      - "8000:8000"

    # Configuramos 2 volúmenes:
    # - jupyterhub-data: para almacenar la configuración y datos de JupyterHub.
    # - ./jupyterhub_config.py: para montar el archivo de configuración personalizado.
    volumes:
      - jupyterhub-data:/srv/jupyterhub
      - ../jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - ../entrypoint.sh:/entrypoint.sh

    command: bash /entrypoint.sh

    environment:
      JUPYTERHUB_ADMIN: admin
      MLFLOW_TRACKING_URI: http://mlflow:5000
      LAKEFS_ENDPOINT: http://lakefs:8000
      LAKEFS_ACCESS_KEY_ID: ${LAKEFS_ACCESS_KEY_ID}
      LAKEFS_SECRET_ACCESS_KEY: ${LAKEFS_SECRET_ACCESS_KEY}

    # Dependencias con mlflow y lakefs
    depends_on:
      mlflow:
        condition: service_healthy
      lakefs:
        condition: service_healthy

volumes:
  jupyterhub-data:
