services:
  lakefs:
    image: treeverse/lakefs:latest
    container_name: simarro-lakefs
    ports:
      - "8001:8000"

    # Configuración de lakefs
    environment:
      LAKEFS_DATABASE_TYPE: local
      LAKEFS_BLOCKSTORE_TYPE: local
      LAKEFS_BLOCKSTORE_LOCAL_PATH: /data
      LAKEFS_AUTH_ENCRYPT_SECRET_KEY: ${LAKEFS_SECRET_KEY}
      LAKEFS_INSTALLATION_USER_NAME: admin
      LAKEFS_INSTALLATION_ACCESS_KEY_ID: ${LAKEFS_ACCESS_KEY_ID}
      LAKEFS_INSTALLATION_SECRET_ACCESS_KEY: ${LAKEFS_SECRET_ACCESS_KEY}

    volumes:
      - lakefs-data:/data

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/_health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  lakefs-data:
