services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: simarro-mlflow
    ports:
      - "5000:5000"

    # Comando de inicialización del servidor MLflow.
    # Se configura para usar SQLite, pero sería interesante utilizar PostgreSQL cuando integremos con la infra de ITI.
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
      --dev
      --allowed-hosts mlflow,localhost,127.0.0.1,172.18.0.0/16

    volumes:
      - mlflow-data:/mlflow

    # Dependencia con lakeFS
    depends_on:
      lakefs:
        condition: service_healthy

    # Comprobar el estado del servicio MLflow
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:5000/', timeout=5).status < 500 else 1)",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mlflow-data:
