repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--line-length=88", "--check"]
        files: .*\.py$

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--check-only"]
        files: .*\.py$

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - pep8-naming==0.15.1
          - flake8-bugbear
          - flake8-comprehensions
        files: .*\.py$

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8-docstrings
        additional_dependencies:
          - flake8-docstrings
        files: .*/test_.+\.py$
