services:
  api-ingauge-engage:
    build:
      context: api
    container_name: caso-d-api-ingauge-engage
    ports:
      - "8000:8000"

  frontend-ingauge-engage:
    build:
      context: frontend
    container_name: caso-d-frontend-ingauge-engage
    ports:
      - "8080:80"
    depends_on:
      - api-ingauge-engage
